// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paperless.REST.DAL.DbContexts;

#nullable disable

namespace Paperless.REST.DAL.Migrations
{
    [DbContext(typeof(PostgressDbContext))]
    [Migration("20260102153323_AddMoreInformation")]
    partial class AddMoreInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paperless.REST.DAL.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentFileVersion")
                        .HasColumnType("integer")
                        .HasColumnName("currentFileVersion");

                    b.Property<int>("CurrentMetadataVersion")
                        .HasColumnType("integer")
                        .HasColumnName("currentMetadataVersion");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deletedByUserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("rowVersion");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pK_documents");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("iX_documents_deletedAt");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("iX_documents_deletedByUserId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("iX_documents_workspaceId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentFileType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("displayName");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fileExtension");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mimeType");

                    b.HasKey("Id")
                        .HasName("pK_fileTypes");

                    b.ToTable("fileTypes", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentLanguage", b =>
                {
                    b.Property<string>("ISO639Code")
                        .HasColumnType("text")
                        .HasColumnName("iSO639Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("ISO639Code")
                        .HasName("pK_documentLanguages");

                    b.ToTable("documentLanguages", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentMetadata", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("createdByUserId");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocumentLanguageISO639Code")
                        .HasColumnType("text")
                        .HasColumnName("documentLanguageISO639Code");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("languageCode");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("DocumentId", "Version")
                        .HasName("pK_documentMetadatas");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("iX_documentMetadatas_createdByUserId");

                    b.HasIndex("DocumentLanguageISO639Code")
                        .HasDatabaseName("iX_documentMetadatas_documentLanguageISO639Code");

                    b.HasIndex("Title")
                        .HasDatabaseName("iX_documentMetadatas_title");

                    b.HasIndex("DocumentId", "CreatedAt")
                        .HasDatabaseName("iX_documentMetadatas_documentId_createdAt");

                    b.ToTable("documentMetadatas", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tagId");

                    b.HasKey("DocumentId", "TagId")
                        .HasName("pK_documentTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("iX_documentTags_tagId");

                    b.ToTable("documentTags", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<Guid>("FileTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fileTypeId");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("originalFileName");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("sizeBytes");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storedName");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploadedAt");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploadedByUserId");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pK_fileVersions");

                    b.HasIndex("FileTypeId")
                        .HasDatabaseName("iX_fileVersions_fileTypeId");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("iX_fileVersions_uploadedByUserId");

                    b.HasIndex("DocumentId", "Version")
                        .IsUnique()
                        .HasDatabaseName("iX_fileVersions_documentId_version");

                    b.HasIndex("OriginalFileName", "UploadedAt")
                        .HasDatabaseName("iX_fileVersions_originalFileName_uploadedAt");

                    b.ToTable("fileVersions", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.ProcessingStatus", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("LastError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("lastError")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("Ocr")
                        .HasColumnType("integer")
                        .HasColumnName("ocr");

                    b.Property<int>("Summary")
                        .HasColumnType("integer")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("DocumentId")
                        .HasName("pK_processingStatuses");

                    b.ToTable("processingStatuses", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("iX_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pK_shares");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("iX_shares_documentId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("iX_shares_token");

                    b.ToTable("shares", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentId");

                    b.Property<Guid>("LengthPresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("lengthPresetId");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.HasKey("Id")
                        .HasName("pK_documentSummaries");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("iX_documentSummaries_documentId");

                    b.HasIndex("LengthPresetId")
                        .HasDatabaseName("iX_documentSummaries_lengthPresetId");

                    b.ToTable("documentSummaries", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.SummaryPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("maxTokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.HasKey("Id")
                        .HasName("pK_summaryPresets");

                    b.ToTable("summaryPresets", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("iX_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("displayName");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("mustChangePassword");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pK_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("iX_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleId");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pK_userRoles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("iX_userRoles_roleId");

                    b.ToTable("userRoles", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_workspaces");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspaceId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userId");

                    b.Property<Guid>("WorkspaceRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspaceRoleId");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pK_workspaceMembers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("iX_workspaceMembers_userId");

                    b.HasIndex("WorkspaceRoleId")
                        .HasDatabaseName("iX_workspaceMembers_workspaceRoleId");

                    b.ToTable("workspaceMembers", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.WorkspaceRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_workspaceRoles");

                    b.ToTable("workspaceRoles", (string)null);
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Document", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_documents_users_deletedByUserId");

                    b.HasOne("Paperless.REST.DAL.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_documents_workspaces_workspaceId");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentMetadata", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_documentMetadatas_users_createdByUserId");

                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithMany("MetadataVersions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_documentMetadatas_documents_documentId");

                    b.HasOne("Paperless.REST.DAL.Models.DocumentLanguage", "DocumentLanguage")
                        .WithMany()
                        .HasForeignKey("DocumentLanguageISO639Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fK_documentMetadatas_documentLanguages_documentLanguageISO639C~");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("DocumentLanguage");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.DocumentTag", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_documentTags_documents_documentId");

                    b.HasOne("Paperless.REST.DAL.Models.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_documentTags_tags_tagId");

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.FileVersion", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithMany("FileVersions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_fileVersions_documents_documentId");

                    b.HasOne("Paperless.REST.DAL.Models.DocumentFileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_fileVersions_fileTypes_fileTypeId");

                    b.HasOne("Paperless.REST.DAL.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_fileVersions_users_uploadedByUserId");

                    b.Navigation("Document");

                    b.Navigation("FileType");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.ProcessingStatus", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithOne("ProcessingStatus")
                        .HasForeignKey("Paperless.REST.DAL.Models.ProcessingStatus", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_processingStatuses_documents_documentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Share", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_shares_documents_documentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Summary", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Document", "Document")
                        .WithMany("Summaries")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_documentSummaries_documents_documentId");

                    b.HasOne("Paperless.REST.DAL.Models.SummaryPreset", "LengthPreset")
                        .WithMany()
                        .HasForeignKey("LengthPresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_documentSummaries_summaryPresets_lengthPresetId");

                    b.Navigation("Document");

                    b.Navigation("LengthPreset");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.UserRole", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_userRoles_roles_roleId");

                    b.HasOne("Paperless.REST.DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_userRoles_users_userId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.WorkspaceMember", b =>
                {
                    b.HasOne("Paperless.REST.DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_workspaceMembers_users_userId");

                    b.HasOne("Paperless.REST.DAL.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_workspaceMembers_workspaces_workspaceId");

                    b.HasOne("Paperless.REST.DAL.Models.WorkspaceRole", "Role")
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_workspaceMembers_workspaceRoles_workspaceRoleId");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Document", b =>
                {
                    b.Navigation("DocumentTags");

                    b.Navigation("FileVersions");

                    b.Navigation("MetadataVersions");

                    b.Navigation("ProcessingStatus")
                        .IsRequired();

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Tag", b =>
                {
                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Paperless.REST.DAL.Models.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
