/*
 * Document Management REST API
 *
 * UI-facing REST API for a Document Management System (.NET 9 + ASP.NET) Public API used by the Web UI to upload, process, search, share, and manage documents. Internal workers (OCR, GenAI summary, indexing) run in separate containers and are not directly exposed here. Optional/nice-to-have features are marked via `x-optional: true` or may return 501 (Not Implemented) until implemented.  ## Key decisions - Runtime: .NET 9 + ASP.NET - Consumers: Internal web UI (future external UIs possible) - Auth: JWT Bearer for users; API Key for workers; PSK (token + password) for guest access - Uploads: Multipart, multiple files supported - Processing pipeline (asynchronous-ready): OCR → GenAI summary → Indexing - Search: free-text + filters; page-based pagination (page/pageSize with 10, 20, 50; default 20, max 100) - Soft-delete with recycle bin; optional hard purge - Workspaces for scoping; sharing via password-protected links - Approvals feature included as optional (can return 501 until implemented) - Problem details: RFC7807 with `traceId` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace API.Controllers
{
    /// <summary>
    /// Health, readiness, diagnostics, and audit logs.
    /// </summary>
    [ApiController]
    //public class AdminController : ControllerBase
    public class AdminController : BaseApiController
    {
        private readonly NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Read-only diagnostics (no secrets)
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/v1/admin/diagnostics")]
        //[Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public virtual IActionResult Diagnostics()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Liveness check
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/health")]
        //[Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public virtual IActionResult Health()
        {
            return Ok(new { status = "OK" });
        }

        /// <summary>
        /// Query audit logs (admin only)
        /// </summary>
        /// <param name="level"></param>
        /// <param name="page"></param>
        /// <param name="pageSize">Number of items per page (default 20; max 100 supported server-side).</param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/v1/admin/audit-logs")]
        //[Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public virtual IActionResult ListAuditLogs([FromQuery (Name = "level")]string level, [FromQuery (Name = "page")]int? page, [FromQuery (Name = "pageSize")]int? pageSize)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Readiness check
        /// </summary>
        /// <response code="200">Ready</response>
        [HttpGet]
        [Route("/ready")]
        //[Authorize]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public virtual IActionResult Ready()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }
    }
}
