/*
 * Document Management REST API
 *
 * UI-facing REST API for a Document Management System (.NET 9 + ASP.NET) Public API used by the Web UI to upload, process, search, share, and manage documents. Internal workers (OCR, GenAI summary, indexing) run in separate containers and are not directly exposed here. Optional/nice-to-have features are marked via `x-optional: true` or may return 501 (Not Implemented) until implemented.  ## Key decisions - Runtime: .NET 9 + ASP.NET - Consumers: Internal web UI (future external UIs possible) - Auth: JWT Bearer for users; API Key for workers; PSK (token + password) for guest access - Uploads: Multipart, multiple files supported - Processing pipeline (asynchronous-ready): OCR → GenAI summary → Indexing - Search: free-text + filters; page-based pagination (page/pageSize with 10, 20, 50; default 20, max 100) - Soft-delete with recycle bin; optional hard purge - Workspaces for scoping; sharing via password-protected links - Approvals feature included as optional (can return 501 until implemented) - Problem details: RFC7807 with `traceId` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Paperless.REST.API.Controllers
{
    /// <summary>
    /// Create and manage password-protected share links for guests.
    /// </summary>
    [ApiController]
    //public class SharingController : ControllerBase
    public class SharingController : BaseApiController
    {
        private readonly NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Create a password-protected share link
        /// </summary>
        /// <param name="id"></param>
        /// <param name="shareCreate"></param>
        /// <response code="201">Created</response>
        [HttpPost]
        [Route("/v1/documents/{id}/shares")]
        [Authorize]
        [Consumes("application/json")]
        //[ProducesResponseType(statusCode: 201, type: typeof(Share))]
        public virtual IActionResult CreateShare([FromRoute (Name = "id")][Required]Guid id, [FromBody]JsonElement body)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Revoke a share
        /// </summary>
        /// <param name="shareId"></param>
        /// <response code="204">Revoked</response>
        [HttpDelete]
        [Route("/v1/shares/{shareId}")]
        //[Authorize]
        public virtual IActionResult DeleteShare([FromRoute (Name = "shareId")][Required]Guid shareId)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get a share configuration
        /// </summary>
        /// <param name="shareId"></param>
        /// <response code="200">OK</response>
        /// <response code="404">Not found</response>
        [HttpGet]
        [Route("/v1/shares/{shareId}")]
        //[Authorize]
        //[ProducesResponseType(statusCode: 200, type: typeof(Share))]
        //[ProducesResponseType(statusCode: 404, type: typeof(Problem))]
        public virtual IActionResult GetShare([FromRoute (Name = "shareId")][Required]Guid shareId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// List share links for a document
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/v1/documents/{id}/shares")]
        //[Authorize]
        //[ProducesResponseType(statusCode: 200, type: typeof(ListShares200Response))]
        public virtual IActionResult ListShares([FromRoute (Name = "id")][Required]Guid id)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }
    }
}
