/*
 * Document Management REST API
 *
 * UI-facing REST API for a Document Management System (.NET 9 + ASP.NET) Public API used by the Web UI to upload, process, search, share, and manage documents. Internal workers (OCR, GenAI summary, indexing) run in separate containers and are not directly exposed here. Optional/nice-to-have features are marked via `x-optional: true` or may return 501 (Not Implemented) until implemented.  ## Key decisions - Runtime: .NET 9 + ASP.NET - Consumers: Internal web UI (future external UIs possible) - Auth: JWT Bearer for users; API Key for workers; PSK (token + password) for guest access - Uploads: Multipart, multiple files supported - Processing pipeline (asynchronous-ready): OCR → GenAI summary → Indexing - Search: free-text + filters; page-based pagination (page/pageSize with 10, 20, 50; default 20, max 100) - Soft-delete with recycle bin; optional hard purge - Workspaces for scoping; sharing via password-protected links - Approvals feature included as optional (can return 501 until implemented) - Problem details: RFC7807 with `traceId` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    //public class WorkspacesController : ControllerBase
    public class WorkspacesController : BaseApiController
    {
        private readonly NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Add a member to a workspace
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <param name="workspaceMemberCreate"></param>
        /// <response code="201">Added</response>
        [HttpPost]
        [Route("/v1/workspaces/{workspaceId}/members")]
        //[Authorize]
        [Consumes("application/json")]
        //[ProducesResponseType(statusCode: 201, type: typeof(WorkspaceMember))]
        public virtual IActionResult AddWorkspaceMember([FromRoute (Name = "workspaceId")][Required]Guid workspaceId, [FromBody]JsonElement body)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Create a workspace
        /// </summary>
        /// <param name="workspaceCreate"></param>
        /// <response code="201">Created</response>
        [HttpPost]
        [Route("/v1/workspaces")]
        //[Authorize]
        [Consumes("application/json")]
        //[ProducesResponseType(statusCode: 201, type: typeof(Workspace))]
        public virtual IActionResult CreateWorkspace([FromBody]JsonElement body)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Delete a workspace
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <response code="204">Deleted</response>
        [HttpDelete]
        [Route("/v1/workspaces/{workspaceId}")]
        //[Authorize]
        public virtual IActionResult DeleteWorkspace([FromRoute (Name = "workspaceId")][Required]Guid workspaceId)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get a workspace
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <response code="200">OK</response>
        /// <response code="404">Not found</response>
        [HttpGet]
        [Route("/v1/workspaces/{workspaceId}")]
        //[Authorize]
        //[ProducesResponseType(statusCode: 200, type: typeof(Workspace))]
        //[ProducesResponseType(statusCode: 404, type: typeof(Problem))]
        public virtual IActionResult GetWorkspace([FromRoute (Name = "workspaceId")][Required]Guid workspaceId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// List workspace members
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/v1/workspaces/{workspaceId}/members")]
        //[Authorize]
        //[ProducesResponseType(statusCode: 200, type: typeof(ListWorkspaceMembers200Response))]
        public virtual IActionResult ListWorkspaceMembers([FromRoute (Name = "workspaceId")][Required]Guid workspaceId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// List workspaces
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/v1/workspaces")]
        //[Authorize]
        //[ProducesResponseType(statusCode: 200, type: typeof(ListWorkspaces200Response))]
        public virtual IActionResult ListWorkspaces()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Update workspace (JSON Merge Patch)
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <param name="workspacePatch"></param>
        /// <param name="ifMatch">Strong ETag of the resource to guard against concurrent updates.</param>
        /// <response code="200">Updated</response>
        /// <response code="412">Precondition failed (ETag mismatch)</response>
        [HttpPatch]
        [Route("/v1/workspaces/{workspaceId}")]
        //[Authorize]
        [Consumes("application/merge-patch+json")]
        //[ProducesResponseType(statusCode: 200, type: typeof(Workspace))]
        //[ProducesResponseType(statusCode: 412, type: typeof(Problem))]
        public virtual IActionResult PatchWorkspace([FromRoute (Name = "workspaceId")][Required]Guid workspaceId, [FromBody]JsonElement body, [FromHeader (Name = "If-Match")]string ifMatch)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 412 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(412, default);
            //TODO: Change the data returned
            return NotImplementedStub();
        }

        /// <summary>
        /// Remove a workspace member
        /// </summary>
        /// <param name="workspaceId"></param>
        /// <param name="userId"></param>
        /// <response code="204">Removed</response>
        [HttpDelete]
        [Route("/v1/workspaces/{workspaceId}/members/{userId}")]
        //[Authorize]
        public virtual IActionResult RemoveWorkspaceMember([FromRoute (Name = "workspaceId")][Required]Guid workspaceId, [FromRoute (Name = "userId")][Required]Guid userId)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);

            throw new NotImplementedException();
        }
    }
}
